# Generated by Django 3.2.9 on 2021-12-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='issued',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
