# Generated by Django 3.2.9 on 2021-12-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_comnets_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Post',
        ),
    ]
